version: '3'

services:
  nginx:
    container_name: pw_local_env-nginx
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - '8030:80'
    volumes:
      - ./packages/webapp:/app
      - ./packages/webapp/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: pw_local_env-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '9030:9001'
    volumes:
      - ./packages/webapp/:/app
    depends_on:
      - db

  db:
    container_name: pw_local_env-db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3330:3306'
    volumes:
      - ./packages/webapp/sql-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./packages/webapp/.env

  admin:
    container_name: pw_local_env-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  cypress:
    container_name: pw_local_cypress
    image: cypress/included:7.2.0
    working_dir: /e2e
    network_mode: host
    volumes:
      - ./packages/test/:/e2e
    depends_on:
      - nginx
